# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'projectAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for projectAPI
  pod 'Alamofire', '~> 5.4'
  pod 'AlamofireNetworkActivityLogger', '~> 3.4'
  pod 'NVActivityIndicatorView'
end
